 # Black formats the Python code
    - repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
          - id: black
    # Flake8 lints the Python code
    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8